name: CI Dev

on:
  push:
    branches: [ main ]

jobs:

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Transfer stack config to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: "22"
          source: "docker-compose.production.yml"
          target: "agora"

      - name: Deploy stack
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          script: |
            cd agora
            sudo env $(cat .env | grep ^[A-Z] | xargs) docker stack deploy -c docker-compose.production.yml agora
